version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@google-cloud/firestore"
    versions:
    - 4.10.0
    - 4.9.1
    - 4.9.2
    - 4.9.3
    - 4.9.6
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: telegraf
    versions:
    - 4.1.0
    - 4.1.2
    - 4.2.0
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: semantic-release
    versions:
    - 17.3.9
    - 17.4.1
