name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run coverage
      - uses: codecov/codecov-action@v1
      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: botHook
          runtime: nodejs12
          region: europe-west3
          credentials: ${{ secrets.GCP_SA_KEY }}
