name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        version: [16.x, 18.x, 20.x]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}
      - run: npm ci
      - run: npm run coverage
      - uses: codecov/codecov-action@v1
