name: Release

on:
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependecies
        run: npm ci
      - name: Running Tests
        run: npm run coverage
      - name: Test coverage
        uses: codecov/codecov-action@v1
    
  gcloud-deploy:
    runs-on: ubuntu-18.04
    environment: "Google Cloud Deploy"
    needs: testing

    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: botHook
          runtime: nodejs12
          region: ${{ secrets.PROJECT_REGION }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          env_vars: 
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}

  release-new-version:
    runs-on: ubuntu-18.04
    environment: "Telegram Messaging"
    needs: gcloud-deploy

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependecies
        run: npm ci
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
        run: npx semantic-release
